feat: install with Homebrew on Linux

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -34,6 +34,15 @@ before_install:
     fi
 
 install:
+  # Install Homebrew on Ubuntu
+  - >
+    if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then
+      if [[ "$WITH_HOMEBREW_ON_LINUX" == "yes" ]]; then
+        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
+        echo "eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)" >> ~/.profile
+      fi
+    fi
+
   # Install Ansible with pip on Ubuntu
   - >
     if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then
@@ -69,17 +78,9 @@ script:
       ansible-playbook tests/test.yml -i tests/inventory --connection=local \
         -e "{'pyenv_install_from_package_manager':true}" \
         || travis_terminate 1
-    else
+    elif [[ "$WITH_HOMEBREW_ON_LINUX" == "yes" ]]; then
       ansible-playbook tests/test.yml -i tests/inventory --connection=local \
-        -e "{'pyenv_install_from_package_manager':false}" \
-        || travis_terminate 1
-    fi
-
-  # Debug idempotence test
-  - >
-    if [[ "$FROM_PACKAGE_MANAGER" == "yes" ]]; then
-      ansible-playbook tests/test.yml -i tests/inventory --connection=local \
-        -e "{'pyenv_install_from_package_manager':true}" \
+        -e "{'pyenv_homebrew_on_linux':true}" \
         || travis_terminate 1
     else
       ansible-playbook tests/test.yml -i tests/inventory --connection=local \
@@ -91,13 +92,19 @@ script:
   - >
     if [[ "$FROM_PACKAGE_MANAGER" == "yes" ]]; then
       ansible-playbook tests/test.yml -i tests/inventory --connection=local \
-      -e "{'pyenv_install_from_package_manager':true}" \
+        -e "{'pyenv_install_from_package_manager':true}" \
+        | grep -q 'changed=0.*failed=0' \
+        && (echo 'Idempotence test: pass' && exit 0) \
+        || (echo 'Idempotence test: fail' && exit 1)
+    elif [[ "$WITH_HOMEBREW_ON_LINUX" == "yes" ]]; then
+      ansible-playbook tests/test.yml -i tests/inventory --connection=local \
+        -e "{'pyenv_homebrew_on_linux':true}" \
         | grep -q 'changed=0.*failed=0' \
         && (echo 'Idempotence test: pass' && exit 0) \
         || (echo 'Idempotence test: fail' && exit 1)
     else
       ansible-playbook tests/test.yml -i tests/inventory --connection=local \
-      -e "{'pyenv_install_from_package_manager':failed}" \
+        -e "{'pyenv_install_from_package_manager':false}" \
         | grep -q 'changed=0.*failed=0' \
         && (echo 'Idempotence test: pass' && exit 0) \
         || (echo 'Idempotence test: fail' && exit 1)
@@ -150,6 +157,11 @@ jobs:
       os: linux
       dist: bionic
       env: ANSIBLE_VERSION='<2.10'
+    - stage: test
+      name: "Ubuntu 18.04 (Bionic) with Ansible 2.9 with Homebrew"
+      os: linux
+      dist: bionic
+      env: ANSIBLE_VERSION='<2.10' WITH_HOMEBREW_ON_LINUX='yes'
 
     - stage: test
       name: "macOS 10.13 (High Sierra) with Xcode 10.1 with Homebrew"
